project:
  type: website

website:
  title: "ISSS608 VISUAL"
  navbar:
    left:
    - text: "Take Home Exercise"
      menu:
        - text: "Takehome Exercise 01"
          href: TakehomeEx01.html
        - text: "Takehome Exercise 02"
          href: TakehomeEx02.html
    right: 
    - text: "About Page"
      href: about.html


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

