project:
  type: website

website:
  title: "ISSS608 VISUAL"
  navbar:
    left:
    - text: "Take Home Exercise"
      menu:
        - text: "Data Preparation"
          href: Data Preparation.html
        - text: "Dashboard Building"
          href: Dashboard Building.html
        - text: "Take Exercise 02"
          href: TakehomeEx02.html
    right: 
    - text: "About Page"
      href: about.html


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

